version: '3.5'

services:

  php:
    container_name: php-${PROJECT_NAME:-default}
    build: .docker/build/php
    volumes:
      - ./src:/var/www/html
    ports:
      - ${PROJECT_PORT:-8080}:80
    depends_on:
      - db
    networks:
      - default
    environment:
      - DEBUG_HOST=${DEBUG_HOST:-cloud9-default}
      - DEBUG_PORT=${DEBUG_PORT:-9000}

  cloud9-casaavance:
    container_name: cloud9-${PROJECT_NAME:-default}
    build: .docker/build/cloud9
    volumes:
      - ./src:/var/www/html
    ports:
      - ${DEBUG_IDE_PORT:-5050}:5050
    environment:
      - PROJECT_NAME=${PROJECT_HOSTNAME:-localhost}
      - PROJECT_HOSTNAME=${PROJECT_HOSTNAME:-localhost}
      - PROJECT_PORT=${PROJECT_PORT:-8080}
      - DEBUG_HOST=${DEBUG_HOST:-cloud9-default}
      - DEBUG_PORT=${DEBUG_PORT:-9000}
    networks:
      - default

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-${PROJECT_NAME:-default}
    restart: always
    tty: true
    volumes:
      - ./.docker/config/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-banco}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    networks:
      - default
    ports:
      - "${DB_PORT:-3307}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

networks:
  default:
    name: ${PROJECT_NAME:-default}
    driver: bridge
